-- MỘC MÂY V8 — Reviews setup (idempotent)
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  rating integer not null check (rating between 1 and 5),
  text text not null,
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

drop policy if exists "Khach duoc xem danh gia" on public.reviews;
drop policy if exists "Khach duoc gui danh gia" on public.reviews;
drop policy if exists "Admin duoc xoa danh gia" on public.reviews;

create policy "Khach duoc xem danh gia"
on public.reviews for select
to anon, authenticated using (true);

create policy "Khach duoc gui danh gia"
on public.reviews for insert
to anon, authenticated
with check (
  char_length(trim(name)) between 2 and 80
  and rating between 1 and 5
  and char_length(trim(text)) between 5 and 1000
);

create policy "Admin duoc xoa danh gia"
on public.reviews for delete
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

grant select, insert on public.reviews to anon, authenticated;
grant delete on public.reviews to authenticated;
grant usage, select on sequence public.reviews_id_seq to anon, authenticated;

create index if not exists reviews_created_at_idx on public.reviews (created_at desc);

-- Add Realtime only if it is not already enabled.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'reviews'
  ) then
    alter publication supabase_realtime add table public.reviews;
  end if;
end $$;

alter table public.reviews replica identity full;
