-- MỘC MÂY V8 — Database security hardening
-- Run this AFTER the existing orders table and reviews table have been created.

-- 1) ORDERS: customers may INSERT only; only role=admin may SELECT/UPDATE/DELETE.
alter table public.orders enable row level security;

drop policy if exists "Admin duoc xem don" on public.orders;
drop policy if exists "Admin duoc cap nhat don" on public.orders;
drop policy if exists "Admin duoc xoa don hang" on public.orders;
drop policy if exists "Khach duoc tao don" on public.orders;

create policy "Khach duoc tao don"
on public.orders
for insert
to anon, authenticated
with check (
  char_length(trim(customer_name)) between 2 and 100
  and char_length(trim(phone)) between 8 and 20
  and char_length(trim(address)) between 5 and 300
  and char_length(coalesce(note, '')) <= 500
  and total >= 0
  and status = 'Mới'
  and jsonb_typeof(items) = 'array'
  and jsonb_array_length(items) between 1 and 30
);

create policy "Admin duoc xem don"
on public.orders
for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admin duoc cap nhat don"
on public.orders
for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admin duoc xoa don hang"
on public.orders
for delete
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- Useful indexes for admin queries.
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);

-- 2) REVIEWS: public read/insert; only Admin may delete.
alter table public.reviews enable row level security;

drop policy if exists "Khach duoc xem danh gia" on public.reviews;
drop policy if exists "Khach duoc gui danh gia" on public.reviews;
drop policy if exists "Admin duoc xoa danh gia" on public.reviews;

create policy "Khach duoc xem danh gia"
on public.reviews
for select
to anon, authenticated
using (true);

create policy "Khach duoc gui danh gia"
on public.reviews
for insert
to anon, authenticated
with check (
  char_length(trim(name)) between 2 and 80
  and rating between 1 and 5
  and char_length(trim(text)) between 5 and 1000
);

create policy "Admin duoc xoa danh gia"
on public.reviews
for delete
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create index if not exists reviews_created_at_idx on public.reviews (created_at desc);

-- 3) Realtime configuration. Safe to run more than once: the DO block checks first.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'reviews'
  ) then
    alter publication supabase_realtime add table public.reviews;
  end if;
end $$;

alter table public.orders replica identity full;
alter table public.reviews replica identity full;

-- IMPORTANT:
-- Keep only the Supabase publishable/anon key in the frontend.
-- NEVER put service_role/secret keys in React, Vite, GitHub, or public files.
-- MỘC MÂY V9 — Đồng bộ dữ liệu + bảo vệ giá đơn hàng + liên hệ + chống spam cơ bản
-- Chạy sau các SQL V8. Script có thể chạy lại nhiều lần.

-- 1) PRODUCT CATALOG — nguồn giá sản phẩm dùng chung cho mọi thiết bị.
create table if not exists public.product_catalog (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 120),
  price numeric(12,0) not null check (price >= 0 and price <= 100000000),
  category text not null check (char_length(trim(category)) between 1 and 50),
  rating numeric(2,1) not null default 5 check (rating between 0 and 5),
  description text not null default '',
  image_url text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.product_catalog enable row level security;
drop policy if exists "Cong khai xem san pham dang ban" on public.product_catalog;
drop policy if exists "Admin quan ly san pham" on public.product_catalog;
create policy "Cong khai xem san pham dang ban"
on public.product_catalog for select to anon, authenticated
using (active = true or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "Admin quan ly san pham"
on public.product_catalog for all to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
grant select on public.product_catalog to anon, authenticated;
grant insert, update, delete on public.product_catalog to authenticated;
grant usage, select on sequence public.product_catalog_id_seq to authenticated;

create or replace function public.set_product_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
drop trigger if exists product_catalog_updated_at on public.product_catalog;
create trigger product_catalog_updated_at
before update on public.product_catalog
for each row execute function public.set_product_updated_at();

-- Seed 6 món mặc định nếu catalog còn trống. Chạy bằng SQL Editor nên không phụ thuộc RLS.
insert into public.product_catalog (id,name,price,category,rating,description,image_url,active)
values
(1,'Matcha Latte Mây Xanh',30000,'Tea',4.9,'Matcha thanh dịu, sữa tươi béo nhẹ và lớp mây kem mịn.','https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=1200&q=85',true),
(2,'Trà Đào Cam Sả Mây',30000,'Tea',4.9,'Trà đào cam sả tươi sáng vị, cân bằng và dễ uống.','https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=1200&q=85',true),
(3,'Cacao Muối Biển Chill',30000,'Cacao',4.7,'Cacao đậm vị cân bằng với lớp kem muối biển dịu mềm.','https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=1200&q=85',true),
(4,'Dâu Kem Sữa Mộng Mơ',30000,'Milk',4.8,'Dâu tươi chua ngọt cùng sữa và lớp kem mịn.','https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1200&q=85',true),
(5,'Trà Vải Hoa Nhài',33000,'Tea',4.8,'Vải ngọt thanh kết hợp hương hoa nhài nhẹ nhàng.','https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=1200&q=85',true),
(6,'Cà Phê Mây',32000,'Coffee',4.7,'Cà phê đậm vừa, hậu vị êm và lớp kem mây mềm.','https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=85',true)
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.product_catalog','id'), greatest((select coalesce(max(id),1) from public.product_catalog),1), true);

-- 2) STORE SETTINGS — đồng bộ tên/địa chỉ/cấu hình giữa điện thoại và máy tính.
create table if not exists public.store_settings (
  id integer primary key default 1 check (id = 1),
  brand text not null,
  email text not null,
  phone text not null,
  address text not null,
  hours text not null,
  bg text not null default '#f7f3e9',
  green text not null default '#315d3a',
  layout text not null default 'soft',
  updated_at timestamptz not null default now()
);
insert into public.store_settings (id,brand,email,phone,address,hours,bg,green,layout)
values (1,'Mộc Mây','hello@mocmay.vn','0900 123 456','12 Đường Lá Nhỏ, Quận 3, TP. Hồ Chí Minh','Thứ Hai – Chủ Nhật · 08:00 – 21:30','#f7f3e9','#315d3a','soft')
on conflict (id) do nothing;
alter table public.store_settings enable row level security;
drop policy if exists "Cong khai xem cai dat cua hang" on public.store_settings;
drop policy if exists "Admin cap nhat cai dat cua hang" on public.store_settings;
create policy "Cong khai xem cai dat cua hang" on public.store_settings for select to anon, authenticated using (true);
create policy "Admin cap nhat cai dat cua hang" on public.store_settings for all to authenticated using ((auth.jwt() -> 'app_metadata' ->> 'role')='admin') with check ((auth.jwt() -> 'app_metadata' ->> 'role')='admin');
grant select on public.store_settings to anon, authenticated;
grant insert, update, delete on public.store_settings to authenticated;

-- 3) SERVER-SIDE ORDER TOTAL — trình duyệt không thể tự giảm giá đơn.
create or replace function public.validate_order_total()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  item_count integer;
  distinct_count integer;
  matched_count integer;
  valid_qty boolean;
  valid_price boolean;
  calculated numeric;
  array_len integer;
begin
  if jsonb_typeof(new.items) <> 'array' then
    raise exception 'Danh sách sản phẩm không hợp lệ';
  end if;
  array_len := jsonb_array_length(new.items);
  if array_len < 1 or array_len > 30 then
    raise exception 'Danh sách sản phẩm không hợp lệ';
  end if;

  select count(*), count(distinct i.id), count(p.id),
         coalesce(bool_and(i.quantity between 1 and 99), false),
         coalesce(bool_and(i.price = p.price), false),
         coalesce(sum(p.price * i.quantity), 0)
  into item_count, distinct_count, matched_count, valid_qty, valid_price, calculated
  from jsonb_to_recordset(new.items) as i(id bigint, price numeric, quantity integer)
  left join public.product_catalog p on p.id = i.id;

  if item_count <> array_len or distinct_count <> item_count or matched_count <> array_len then
    raise exception 'Sản phẩm trong đơn không hợp lệ';
  end if;
  if not valid_qty then
    raise exception 'Số lượng sản phẩm không hợp lệ';
  end if;
  if not valid_price then
    raise exception 'Giá sản phẩm đã thay đổi. Vui lòng tải lại giỏ hàng';
  end if;
  if new.total <> calculated then
    raise exception 'Tổng đơn hàng không hợp lệ';
  end if;
  return new;
end;
$$;
drop trigger if exists orders_validate_total on public.orders;
create trigger orders_validate_total
before insert or update of items,total on public.orders
for each row execute function public.validate_order_total();

-- 4) CONTACT MESSAGES — form liên hệ thực sự gửi về hệ thống.
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 100),
  email text not null check (char_length(trim(email)) between 5 and 160),
  subject text not null check (char_length(trim(subject)) between 2 and 160),
  message text not null check (char_length(trim(message)) between 5 and 2000),
  created_at timestamptz not null default now()
);
alter table public.contact_messages enable row level security;
drop policy if exists "Khach duoc gui lien he" on public.contact_messages;
drop policy if exists "Admin xem lien he" on public.contact_messages;
drop policy if exists "Admin xoa lien he" on public.contact_messages;
create policy "Khach duoc gui lien he" on public.contact_messages for insert to anon, authenticated with check (char_length(trim(name)) between 2 and 100 and char_length(trim(email)) between 5 and 160 and char_length(trim(subject)) between 2 and 160 and char_length(trim(message)) between 5 and 2000);
create policy "Admin xem lien he" on public.contact_messages for select to authenticated using ((auth.jwt() -> 'app_metadata' ->> 'role')='admin');
create policy "Admin xoa lien he" on public.contact_messages for delete to authenticated using ((auth.jwt() -> 'app_metadata' ->> 'role')='admin');
grant insert on public.contact_messages to anon, authenticated;
grant select, delete on public.contact_messages to authenticated;
grant usage, select on sequence public.contact_messages_id_seq to anon, authenticated;

-- 5) Chống spam cơ bản ở database: tối đa 3 review cùng tên trong 30 phút.
create or replace function public.prevent_review_spam()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (select count(*) from public.reviews r where lower(trim(r.name)) = lower(trim(new.name)) and r.created_at > now() - interval '30 minutes') >= 3 then
    raise exception 'Bạn đã gửi quá nhiều đánh giá trong thời gian ngắn';
  end if;
  return new;
end;
$$;
drop trigger if exists reviews_spam_guard on public.reviews;
create trigger reviews_spam_guard before insert on public.reviews for each row execute function public.prevent_review_spam();

create index if not exists product_catalog_active_idx on public.product_catalog(active);
create index if not exists contact_messages_created_at_idx on public.contact_messages(created_at desc);
