create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  rating integer not null check (rating between 1 and 5),
  text text not null,
  created_at timestamptz not null default now()
);
alter table public.reviews enable row level security;
drop policy if exists "Khach duoc xem danh gia" on public.reviews;
create policy "Khach duoc xem danh gia" on public.reviews for select to anon, authenticated using (true);
drop policy if exists "Khach duoc gui danh gia" on public.reviews;
create policy "Khach duoc gui danh gia" on public.reviews for insert to anon, authenticated with check (true);
drop policy if exists "Admin duoc xoa danh gia" on public.reviews;
create policy "Admin duoc xoa danh gia" on public.reviews for delete to authenticated using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
grant select, insert on public.reviews to anon, authenticated;
grant delete on public.reviews to authenticated;
grant usage, select on sequence public.reviews_id_seq to anon, authenticated;
alter publication supabase_realtime add table public.reviews;


-- MỘC MÂY: quyền xóa đơn chỉ dành cho Admin
alter table public.orders enable row level security;
drop policy if exists "Admin duoc xoa don hang" on public.orders;
create policy "Admin duoc xoa don hang"
on public.orders for delete to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
grant delete on public.orders to authenticated;

-- Cho Supabase Realtime gửi sự kiện DELETE
alter table public.orders replica identity full;
